# Instagram Secrets
INSTAGRAM_KEY: '51010b82dbcb4843800bb3c72c89e226'
INSTAGRAM_SECRET: ‘bad18768a4ff41bcae5ea5063d299bcb’ 

# Twitter Secrets
TWITTER_KEY: '7BTtKDM28ndE1QLMAxqlR9Wm2'
TWITTER_SECRET: 'jlgeeE3UVtCrZJ9x90cZmRG3QvSqbqXjDTn0P7PBZkuPbZN5Vx'
TWITTER_TOKEN: '3220603789-hsiki6vRkCCa643LuowOxHGhOK9940aUPi24URZ'
TWITTER_TSECRET: 'EzpLCT3geRQawW4mdcZt12nvVPRlAeOG2bTYZNu47CjAC'
